---
- name: Gather installed package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Install MySQL Server
  ansible.builtin.apt:
    name: mysql-server=8.0.*
    state: present
    update_cache: true
  become: true
  when: "'mysql-server' not in ansible_facts.packages"

- name: Ensure MySQL service is running
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true

- name: Set MySQL root password
  community.mysql.mysql_user:
    name: root
    host: "localhost"
    password: "{{ mysql_root_password }}"
    priv: "*.*:ALL,GRANT"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
    check_implicit_admin: true
    column_case_sensitive: false
  when: "'mysql-server' not in ansible_facts.packages"

- name: Create k3s database
  community.mysql.mysql_db:
    name: "{{ k3s_db_name }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Create k3s database user
  community.mysql.mysql_user:
    name: "{{ k3s_db_user }}"
    password: "{{ k3s_user_password }}"
    priv: "{{ k3s_db_name }}.*:ALL"
    host: "%"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    state: present

- name: Allow MySQL to listen on all interfaces
  ansible.builtin.lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
  notify: Restart mysql
