---
- name: Install base dependencies
  ansible.builtin.apt:
    name:
      - python3-pymysql
      - bash-completion
      - ufw
    state: present
    update_cache: true

- name: Configure firewall
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop: [6443, 22, 80, 443]
