---
- name: Install base dependencies
  ansible.builtin.apt:
    name:
      - python3-apt
      - python3-pymysql
      - bash-completion
      - ufw
    state: present
    update_cache: true
  become: true

- name: Configure firewall
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - 22
    - 6443
    - 80
    - 443
