---
- name: Add Traefik Helm repository
  kubernetes.core.helm_repository:
    name: traefik
    repo_url: https://traefik.github.io/charts

- name: Install Traefik
  kubernetes.core.helm:
    release_name: traefik
    chart_ref: traefik/traefik
    release_namespace: traefik
    create_namespace: true
    release_values:
      deployment:
        kind: DaemonSet
      ports:
        web:
          hostPort: 80
        websecure:
          hostPort: 443
      service:
        type: ClusterIP
    update_repo_cache: true
